AduanaBundle\Entity\Concepto:
    type: entity
    table: Concepto
    id:
        idconcepto:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idConcepto
            generator:
                strategy: IDENTITY
    fields:
        nombreConcepto:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: nombreConcepto
    lifecycleCallbacks: {  }
